### PR TITLE
Docs: correct name

### PR DESCRIPTION
**Pull request by Beginner-Go**

### CODE REVIEW

**Comment by 1715173329** [comment]
I don't see any point of this change.

**Comment by Beginner-Go** [comment]
> I don't see any point of this change.

官方是这种命名规范

**Comment by ElonH** [comment]
It's just a init script, I think it will be deleted soon after installation.

**Comment by Beginner-Go** [comment]
> It's just a init script, I think it will be deleted soon after installation.

是的 在系统启动后会自动删除，在 /rom/etc/uci-defaults 下能看见

**Comment by 1715173329** [comment]
Thanks for PR.

**Pull request merged**
